/*
 * HmChatGptWeb v 1.1.1.4
 *
 * Copyright (c) 2025 Akitsugu Komiyama
 * under the MIT License
 */


hidemaruversion "9.39.99";

setcompatiblemode 0x08000000;

jsmode  @"WebView2\HmChatGptWeb";

js {

// ------------- 会話エンジンの設定項目 -------------

const baseUrl = "https://chatgpt.com/";

const renderPaneCustomParam = {
    place: "rightside",            // leftside | rightside | upside | downside
    size: 900,                     // 左や右の配置の時は、横幅のこと。上や下の配置の時は縦幅のこと。
                                   // ChatGptのサイトに限っては、900以上の幅があることが必要。450なども指定した場合でも一瞬は幅が広くなる。
};

const isOneAtTimeAIRenderPane = 1; // AI関連のレンダリング枠は(他の種類のAIも含め)１つだけにする。(複数起動しそうになると、前のものが閉じる）

// --------------------------------------------------

const renderPaneTargetName = "HmChatGptWeb";

const currentMacroDirectory = currentmacrodirectory();

const script = hidemaru.loadTextFile(currentMacroDirectory + "\\HmConvAIWeb.js");
eval(script);

function returnMinimumWindowSize() {
    if (renderPaneCustomParam.size < 900) {
        return {size:900};
    }
    
    return {};
}

// 初回の時の特別なパラメータ
function firstParamDecorator(baseUrl, text) {
    // スペースしかなければ、空文字
    text = text.trim() === "" ? "" : text;
    
    // URLの構築
    const absoluteUrl = new URL(baseUrl);
    const params = new URLSearchParams({ q: text });
    absoluteUrl.search = params.toString();
    
    return { ...{url: absoluteUrl.href}, ...{size: returnMinimumWindowSize()} };
}

// 最初のAI会話においては、キー送信処理などは不要。(ChatGptは１発目の質問だけはURL処理できるため)
function firstQuestionOnlyOpenWindow() {
    return true;
}

// 最低サイズがある程度ないと、ChatGPTは「リターンキー」では送信できない。
function secondParamDecorator(baseUrl, text) {
    return returnMinimumWindowSize();
}

function onPrevKeySendDecorator() {
    try {
        com.SendShiftEscSync();
    } catch(e) {
    }
}

doMain();

}
